### ISSUE TITLE
[Feature request] Add link list support to megadl

### ISSUE THREAD

**Issue by typhoon71** [megous/megatools#124]
If possible could you add support for file list?
I'm thinking something along wget lines (-i switch, ie wget -i list.txt, where list.txt is a list of links); it could be megadl -i list.txt, and have options to not download already downloaded files.
What about it?

**Comment by lucas794** [comment]
You can do it with a bash file if you want.

files=(  "link1", "link2" "link3" )
for i in "${files[@]}"
do
    megadl $i
done

**Comment by typhoon71** [comment]
well, I know I can make a script that parses a list, but I was thinking of something incorporated into the megadl binary itself, like the example wget function I wrote about.
btw, your script would need to be edited while I wanted to keep the list separated (and parsed later by the binary. Script would be reused and list could be any output.

**Comment by lucas794** [comment]
also you can edit main source , if you know a little of C , but well , the main idea is nice to add to future!

**Comment by typhoon71** [comment]
Well, sadly I can't program.
If I could I would probably submit a patch for that and wouldn't be asking.
Well, let's hope for a nipe person with skill and free time.

**Comment by megous** [comment]
Megatools are supposed to be simple, in order to be easy to understand and scriptable.

You can do what you want by creating a wrapper script around megadl that keeps a list of already downloaded links, and if the link in the provided list is not one of those, calls megadl and adds the link to the downloaded links list on success.

Something like what lucas794 suggested.

To me this is the best way to keep command-line utilities like megatools easy to understand, maintain and use.

**Comment by mantielero** [comment]
Just for the record, there is a tool [mego](https://github.com/scotow/mego) which wraps `megadl` to do exactly that.
