### ISSUE TITLE
auto retry in case of failed upload

### ISSUE THREAD

**Issue by sagiegurari** [megous/megatools#130]
I use the megacopy to upload entire directories.
every once and a while, few files fail (it states it can't connect to server) and I rerun it again after everything finishes since it does continue to next file and is able to upload correctly the next files.
it would be nice if you could try to retry automatically (up to 3 times or so).
it would make sense for the megacopy operation which doesn't work on specific file.

**Comment by megous** [comment]
Hi it does retry API requests many times with exponential backoff. Data operations themselves are not retried.

**Comment by sagiegurari** [comment]
thanks.

**Comment by Xananax** [comment]
I'm in this case too. I'm syncing a huge folder (several GB), and I've been re-running the tool since this morning. Is there a way to at least get a list of all failed downloads?

I would like at least a way to hide "ERROR: File Already exists"

This doesn't work:

```
megacopy --local ./some-dir --remote /Root/some-dir --download | grep -v "ERROR: File already"
```

So the only way to know if every one of my 300+ files has synced is to stare at my terminal and check that there aren't any "F" or any "ERROR: Download failed".

Is there a better way?

Also, I don't know if this warrants it's own thread, but it seems to me the same files are getting "Download failed", with a mention "MAC Mismatch". It's difficult to be certain they're the same files for the reason stated above.

**Comment by Xananax** [comment]
Yup, it's always the same files, almost certain. Is there any way to know why?

**Comment by megous** [comment]
@Xananax Download resumption is implemented now, and this should work.

Uploads can't be resumed reliably. Only during some unknown time window. So the curent technique of re-running the megacopy if anything failed, is the only one, ATM.

There's a plan for automatic resumption in case of temporary network issues, but that's not implemented yet.

**Comment by megous** [comment]
Automatic upload resumption is also implemented now for ongoing transfers. Megatools will retry a few times if part of the upload fails and the failure seems transient.
