### ISSUE TITLE
Modified Date is actually Created Date

### ISSUE THREAD

**Issue by ronky** [megous/megatools#141]
Ahoj Ondro,

if i run the megals -hnlR --header - in the header says "Mod. Date".
If you look via webbrowser mega says "Created Date". Is it the same? I don't think it corresponds to the modified date of the physical file.
It confused me a bit when writing my sync scripts. 

Zdravi,
Martin Ronky

**Comment by megous** [comment]
Cau Martine, :)

yes, it's the same. Mega stores only a single timetamp per file.

regards,
  o.

**Comment by ronky** [comment]
so maybe change the name in the --header? :)

**Comment by megous** [comment]
I don't know. It is just a generic timestamp, in the JSON data it is called simply 'ts' and client can set it as it sees fit. I'll definitely use it as modification time in order for future sync command to work based on size/mod. time.

**Comment by megous** [comment]
Or more precisely it is a filesystem node creation time, and you can't modify existing nodes, so you have to create new filesystem nodes, whenever you change something in a "file". Therefore from a user perspective, it could be thought of as a file modification time, because megatools creates a filesystem abstraction over mega's filesystem nodes tree.
