### ISSUE TITLE
CENTOS 6.7 - configure: error: Glib 2.32.0 or later is required to build megatools

### ISSUE THREAD

**Issue by williamwmd** [megous/megatools#152]
Hello,
Megatools is compatible in CENTOS 6.7 64bits?

If necessary you can connect the vps below to test
Details:
IP: 45.55.162.68
USER: root
PASSWORD: megatoolscentos67

Commands:
yum update
yum  install glib-networking gcc make glib2-devel libcurl-devel openssl-devel gmp-devel tar gcc make glib2-devel libcurl-devel openssl-devel gmp-devel wget
wget http://megatools.megous.com/builds/megatools-1.9.95.tar.gz
tar xzf megatools-1.9.95.tar.gz
cd megatools-1.9.95
./configure && make && make install && ldconfig

ERROR:
checking for GLIB - version >= 2.32.0... no
*** Could not run GLIB test program, checking why...
*** The test program failed to compile or link. See the file config.log for the
*** exact error that occured. This usually means GLIB is incorrectly installed.
configure: error: Glib 2.32.0 or later is required to build megatools

**Comment by megous** [comment]
You can check version of glib with yum, to see what is installed there.

**Comment by williamwmd** [comment]
[root@megatoolsCENTOS67 ~]# rpm -q glibc
glibc-2.12-1.166.el6.x86_64

You have the command to update the glib?

**Comment by megous** [comment]
That's the wrong package. No I don't. If uptodate centos 6 doesn't provide new enough glib2 package, you can build it yourself, but I don't provide support for that.

**Comment by bizlevel** [comment]
Same problem. Also too CentOS. 
Possible to downgrade source for this glib 2.1x ?
Is it really has some decencies in code, to need higher glib version?

**Comment by megous** [comment]
You may try.

**Comment by bizlevel** [comment]
Of course..
I changed version to 2.28.0
but result are next:
```
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.16... yes
checking for GLIB - version >= 2.28.0... yes (version 2.28.8)
checking for OPENSSL... yes
checking for LIBCURL... yes
checking for FUSE... yes
./configure: line 5056: syntax error near unexpected token `else'
./configure: line 5056: `else'


```

**Comment by csebe** [comment]
Hi, same problem, solved as per here: 
http://it-quirks.blogspot.hu/2016/09/installing-megatools-on-centos-6.html

**Comment by locvfx** [comment]
Thank you **csebe**, You made my day!

**Comment by locvfx** [comment]
Guys, this is how I install megatool on Centos 6

# 
yum groupinstall "Development Tools"
yum install glib*
yum install fuse fuse-devel

## Well, at this point you might get error with glib because the version which shipped with centos is lower than the required version, We need to complied  ourself. Here is the guilde:

cd /root/
mkdir glib-source  
cd glib-source/  
wget http://ftp.gnome.org/pub/GNOME/sources/glib/2.32/glib-2.32.4.tar.xz 
xz -d glib-2.32.4.tar.xz 
tar zxf glib-2.32.4.tar.xz  
cd glib-2.32.4/  
./configure --prefix=/usr/local/glib-2.32
make  
make install  

## OK now we start downloading megatool
cd /root/
wget https://megatools.megous.com/builds/megatools-1.9.97.tar.gz
tar zxf megatools-1.9.97.tar.gz
cd megatools-1.9.97
./configure && make && make install && ldconfig

# Alright, we are almost there. Let's test whether it works
# Authorize the tool, we make 
nano /root/.megarc

## Enter your login information and save the file (Control-X , [Y] )
[Login]
Username = Your_Mega_Username
Password = Your_Mega_Password

# Protect the file
chmod 640 /root/.megarc

# Almost there, let's list your files and folders
megals 

# Congratulations, you are done
