### ISSUE TITLE
Password problem

### ISSUE THREAD

**Issue by venuxweb** [megous/megatools#177]
Hi,

Mega use password like : DEfnkj12/.:,@ç_jkfnbfF44GF
Or
G,.'yfi&%gj;64?+96

These don't work with megatools.

Is there a way to do it?

Regards

**Comment by megous** [comment]
How are you using them.

**Comment by venuxweb** [comment]
megadf -u "email@hotmail.com" -p "DEfnkj12/.:,@ç_jkfnbfF44GF" --total

**Comment by megous** [comment]
Are you using windows?

**Comment by venuxweb** [comment]
Linux, debian

**Comment by megous** [comment]
It should work then. Unless you have some non UTF-8 locale setup. Does it work when you enter it via password prompt?

**Comment by venuxweb** [comment]
Hi,

locale LANG=fr_FR.UTF-8

When I put password prompt :
ERROR: Can't login to mega.nz: API call 'us' failed: Server returned error ENOENT

**Comment by venuxweb** [comment]
Can you try with that password for example?

DEfnkj12/.:,@ç_jkfnbfF44GF

**Comment by venuxweb** [comment]
Is it working for you!?

**Comment by megous** [comment]
I'm just collecting the information. I don't have time to work on it right away.

**Comment by megous** [comment]
Generally I would say it's not a good idea to use non-ASCII characters in passwords, because those characters can be represented in multiple ways in UTF-8. If all systems using that password will not apply the same normalization technique before generating the password key or hash, or whatever, you will not be able to login in one of them. Mega does not apply normalization, AFAIK, so there's no way for megatools to make sure the input to PK generator is the same as when using mega.nz website.

**Comment by megous** [comment]
Closing, can't do much about UTF-8 issue.
