### ISSUE TITLE
Some files always fail

### ISSUE THREAD

**Issue by Xananax** [megous/megatools#216]
Related to #130 somehow, I suppose.

I've verified; over about 30 attempts to sync a mega directory with megacopy, the same specific files always fail. I have no idea what they have in common. I'm syncing a library of ebooks, so they're all epub/mobi. Most succeed, but some just fail. I can't see any common denominator. Sometimes it's very small files, sometimes big. The error is always "Mac Mismatch".

It's not absolutely systematic, though; Each time I try to sync, one or two additional files succeed. About 20% didn't the first time (the total is 3000 ebooks for 15Gigs, so about 600 books initially failed), since then, every attempt to sync often adds one book or two, 5 at most, sometimes none.

I'm not even sure the problem is megatools related, but since I use official mega client on multiple PCs without problems, I assume it is.

**Comment by Xananax** [comment]
Nope, rectification; after some files managed to download after several attempts, a bunch just never succeed. I'm left with 202 files that systematically fail. Any solution?

**Comment by Xananax** [comment]
I tried downloading one of the failing files with megaget in a `while true` loop. Over about a hundred trials, it seems the download almost always fails at 1%, but sometimes 5%, 57%, in one case, 87% (same file). The behavior is thus very erratic. I wish I could help more, but I'm not much of a coder and I couldn't really make enough sense of the source to be more helpful.

**Comment by megous** [comment]
Mac mismatch means that file content don't match MAC (message authentication code) that was stored along with other metadata when uploading the file.

This may mean only two things:
- the content got corrupted
- the mac key/metadata got corrupted
  (or both)

Given that you say that download stops at certain point without getting to 100% and then you get the MAC error, it seems that download is not finished, yet megatools procedes as if it did succeed, and tries to verify the MAC instead of failing immediately and reporting download error.

I checked the codepath but there's no ovious way, aside from libcurl (HTTP client library) reporting success, while it failed in reality.

If you want, you can send sample link to megous@megous.com. You can encrypt it with my public GPG key if you like. (https://megous.com/pgp)

**Comment by Xananax** [comment]
Thanks for taking a look, I sent an email with a few samples of failing files to the email your provided

**Comment by Xananax** [comment]
After @megous checked my problem, he concluded (and I agree) the issue was most likely from mega itself; the same files give out an error when downloaded through the web interface. They are fine, though; only the metadata is incorrect; for all means and purposes, however, they are unusable (unless you want to salvage them from your browser cache manually).

I've reached out to mega support in hope of a solution, I will be reporting here for anyone else with this problem if I get an answer.

**Comment by sixtyfive** [comment]
@Xananax, have Mega support ever come back to you about this? Facing the same problem...

**Comment by Xananax** [comment]
If I remember correctly, they told me their filters detected that one of my files was a pirated thing. It was not true, it was a book I legitimately bought off Kobo.com, and then manually removed the DRM off of, but they said they could do nothing about it. I deleted the file and the sync resumed, but that made me not want to use mega anymore.
I use PCloud now, as well as my own Nextcloud
