### ISSUE TITLE
Support for HTTP Range header / Partial file download support

### ISSUE THREAD

**Issue by kelvinhammond** [megous/megatools#23]
There should be an option in the megaget and megadl to support downloading a range of bytes. It should also be possible to output the file contents to stdout or a file pipe. With this feature one could pipe the contents of a download to another command or get just part of a file.

**Comment by megous** [comment]
Issue here is that mega.nz MAC validation only works for the full data. So by downloading only parts of the file you risk all kinds of nasty things, because it's impossible to validate the downloaded data are ok (not corrupted, not manipulated, etc.).

Anyway it's failry easy to implement at this point, so if anyone still needs this, re-open.
