### ISSUE TITLE
CURL Error(s) on MacOS

### ISSUE THREAD

**Issue by SainteCelery** [megous/megatools#236]
> MACHINE:~ USER$ megaget --path /Volumes/LOCAL/FOLDER '/Root/REMOTEFOLDER/REMOTEFILE.mkv'
ERROR: Download failed for '/Root/REMOTEFOLDER/REMOTEFILE.mkv': Data download failed: CURL error: Failure when receiving data from the peer

And....

> MACHINE:~ USER$ megacopy --remote /Root/REMOTEFOLDER --local /Volumes/LOCAL/LOCALFOLDER --download —username 'NAMEatEMAILdotcom' --password 'USERPASSWORD'
D /Volumes/LOCAL/LOCALFOLDER
F /Volumes/LOCAL/LOCALFOLDER/REMOTEFILE.mkv
ERROR: Download failed for /Root/REMOTEFOLDER/REMOTEFILE.mkv: Data download failed: CURL error: Failure when receiving data from the peer

**Comment by megous** [comment]
Does it happen only with big files? Does it happen at the beginning or sometime during download?

**Comment by SainteCelery** [comment]
No, similarly sized files have downloaded without issue. So far, it's happened at the beginning of dl'ing a folder of files and on the last file in a folder. I've gotten around it at the moment by moving the files out of the folder entirely & putting them right in Root; this appears to be working, but it's crapped out previously at 1.6GB of 2.6GB files.

**Comment by megous** [comment]
Location of the files is certainly irrelevant. I suppose it is a intermittent issue then.

The error says that server closed connection (or it ended in some other way) for some reason, during reception of the response. Perhaps megatools can retry the download from where it ended. That should solve the issue.

**Comment by SainteCelery** [comment]
You’re probably right that the location is irrelevant and including a retry function will be useful in many scenarios. However, megacopy has also had trouble with local paths containing more than three subdirectories so, perhaps, path reading is being truncated for some reason. You’d know better than I.

**Comment by nirax** [comment]
I too am seeing the same error with megaput. I have checked with more than one accounts. This error started appearing about 3-4 days back. I have tried uploading the exact same files which were uploaded without hitch and now they refuse to upload.

There is a pattern to it ... files larger than 60 Mb seem to be affected. And always the upload is aborted around 40-42 MB mark. This is what I get  -

ERROR: Upload failed for '/home/frend/repositories/BackupRepo/VeryImportantDocs-2016-11-21.7z': Data upload failed: CURL error: Failed sending data to the peer

I am on Ubuntu 15.10. I am using megatools as available from the ubuntu repos. version info -

megatools 1.9.95 - command line tools for Mega.co.nz

Written by Ondřej Jirman <megous@megous.com>, 2013
Go to http://megatools.megous.com for more information

**Comment by megous** [comment]
That's a fairly old version of megatools. The current is 1.9.98.

Mega's web client does multiple small data requests, usually 1MB in size, while megatools uploads the data in one big request for the entire file. Perhaps mega servers are dropping the ball on the longer/bigger requests, because their tools don't need them.

I'll try uploading a few larger files, to see if I can reproduce this.

**Comment by megous** [comment]
I just uploaded a 300MB file without an issue. Though I might try to implement the segmented upload. Megatools would upload in 1-10MB chunks and save the state between each segment in order to be able to restart from that point. So if the server drops connection like in your case, it would just rollback to the end of the previous segment, and retry from there.

**Comment by nirax** [comment]
I upgraded megatools to -

megatools 1.9.98 - command line tools for Mega.nz
Written by Ondřej Jirman <megous@megous.com>, 2013
Go to http://megatools.megous.com for more information

The problem persists. For some reason the uploads are always aborted at 40-42 MB mark. Smaller files pose no problem.

One more thing, if it is relevant. I get this warning message very frequently : 

WARNING: Skipping FS node aFYkjCQQ because it has malformed attributes

There are always dozens of such warning displayed before any useful work gets done.

**Comment by liar666** [comment]
I'm currently having the same problem with a very large file (15Go) with megatools-1.10.0-win64

Using megaget reports error
"Data download failed: CURL error: Failure when receiving data from the peer"
Using megacopy simply ignores the file

:[[[[[

**Comment by megous** [comment]
Try with 1.10.1.
