### ISSUE TITLE
megacopy with crontab doesn't work

### ISSUE THREAD

**Issue by ALFONE** [megous/megatools#247]
If I use prompt to send `megacopy` command with --username and --password (also tried -u and -p) parameters it works. So I put the entire command on a `copy.sh` file and run it with crontab. It returns this error:

`ERROR: Can't login to mega.nz: API call 'us' failed: Server returned error ENOENT`

I use the fullpath to megacopy in the command (Also tried without).
I have CentOS 7 64 bit on my server.

**Comment by megous** [comment]
Running "sh copy.sh" from terminal works?

**Comment by ALFONE** [comment]
No it doesn't, same error

**Comment by megous** [comment]
Sorry, I have no idea. You may try comparing --debug=api output between the calls.

It might be different escaping for parameter values between different shells, if you're using zsh or bash and then cron uses sh. Or just use .megarc to provide the password, which should be somewhat safer than command line, because then the password is not visible by any other process on the system.

**Comment by ALFONE** [comment]
Yeah I used --password parameter because megatools doesn't find .megarc file even if I put it on /home/name/ directory or megatools directory. I also tried --config ~/.megarc but no success.

I'll try with --debug=api tonight.
