### ISSUE TITLE
megadl fails to parse URL of a folder within an encrypted folder

### ISSUE THREAD

**Issue by Wallacoloo** [megous/megatools#254]
Example:
```
$ megadl 'https://mega.nz/#F!aEgWwbjI!qeXRsnrEMfr5dOyF8ft0_g!rUYhFKLJ'
WARNING: Skipping invalid Mega download link: https://mega.nz/#F!aEgWwbjI!qeXRsnrEMfr5dOyF8ft0_g!rUYhFKLJ
```

Whereas the following (removing everything after the last exclamation point) works fine:
```
$ megadl 'https://mega.nz/#F!aEgWwbjI!qeXRsnrEMfr5dOyF8ft0_g'
Downloaded S01/[...]
Downloaded S02/[...]
[...]
```

In the web interface, that last exclamation point in the URL serves to load only the /S01/ folder instead of the entire / directory. The expected behavior when provided to `megadl` would therefore be to download only the contents of /S01/.

**Comment by megous** [comment]
That's probably some new feature of the new mega.nz website. Megatools was based on reverse engineering of the old mega.co.nz one.

I'll not be implementing this feature. I'll keep it here if anyone will want to take a stab at this.

**Comment by christarazi** [comment]
Seems like what's causing the warning message is the folder_regex is failing to match the input. I fixed the regex to accept inputs such as @Wallacoloo's example. Here it is. You can also view it [here](http://www.regexr.com/).

```
^https?:\/\/mega(?:\.co)?\.nz\/#F!([a-z0-9_-]{8})!([a-z0-9_-]{22})(![a-z0-9_-]{8})?$
```

Something to note though: the last capture group contains an `!` which would need to be ignored in the code. 

What needs to be done now is to capture the 3rd group (the last one) in the regex above, and pass that on to `mega_session_open_exp_folder()` which handles opening the MEGA folder and populating a list that contains all the files and directories inside said MEGA folder. The problem is that I do not know the URL scheme of MEGA and how to utilize the extra group at the end of the URL that specifies a particular folder. Any ideas for this @megous? I could not find anything helpful in the MEGA documentation?

**Comment by megous** [comment]
Hi it looks like it is a filesystem node handle. It might be enough to let the mega_session_open_exp_folder() do its thing and then search for the node matching the folder handle from the 3rd capture in the filesystem node list and make it a root folder when building the path map.

**Comment by MrBrax** [comment]
I'm getting

> WARNING: Skipping FS node 0Z5gEZJJ because it's name is invalid 'root://\*\*\*\*/'
> WARNING: Skipping FS node RcAlEaIS because it's name is invalid '\*\*\*\*'
> WARNING: Skipping FS node gYYgwSLC because it's name is invalid '\*\*\*\*'
> ERROR: EXP folder fs has multiple toplevel nodes? Weird!

when i'm trying to download a subfolder, was this recently broken?

**Comment by megous** [comment]
This is unrelated. Node names are weird, as noted - filename can't contain / and node names are filenames.

Looks like you're trying to download some messed up exported folder generated by some other tool.

**Comment by MrBrax** [comment]
I'm copying the link from the address bar in my browser, in a shared folder.

**Comment by megous** [comment]
Link is fine. The content behind it is not.

**Comment by MrBrax** [comment]
Well i can download it fine in the browser, shouldn't this tool be able to, too?

**Comment by christarazi** [comment]
Can you post the links in question?

**Comment by MrBrax** [comment]
Not really, you _do_ know what mega is like most commonly used for, right? :/

I guess i kinda expected this.
