### ISSUE TITLE
suggestion for megacopy.exe  : --overwrite-if-different-size

### ISSUE THREAD

**Issue by aaz1887** [megous/megatools#274]
I suggest you to make an additional switch to megacopy.exe, such as --overwrite-if-different-size
for upload a file with equal name if file-size in mega-cloud is different.

Excuse my poor English. Thank you very much

**Comment by jiggunjer** [comment]
Seconded, though I wouldn't recommend filesize; maybe md5? Or just a dumb --overwrite switch. Current behavior is to give a non-terminating error if the target file/folder exists, making it impossible to update text files that change.

My fix, for the time being, is to remove all duplicate files/folders first, then upload from the newer source. This is not perfect because sometimes files aren't changed but they still get replaced.

**Comment by i30817** [comment]
I'd like to go further and have a option to *delete* files which exist in the local folder but not the cloud one. This is because many people share public folders as 'updateable' and delete files there, and i want the *last version* locally not 'the last and what existed before'.

**Comment by groundstack** [comment]
This would be a nice feature. Right now as far as I know it just skips modified files so you are never sure if you have the latest version on mega.nz. Is there a workaround that does not involve re-uploading all existing files? Thanks!

**Comment by penright** [comment]
It might be easier just to ask for rsync capabilities.
On second thought, can we have rsync capabilities? :-)

**Comment by megous** [comment]
No md5. Mega doesn't even have a proper timestamping for uploaded files (there's "ts" field, but it only stores time of upload, not a modification time of the original file, so it's useless for comparison). It is possible to store whatever extra metadata along the filesystem nodes, but it would only work with megatools and would not be compatible with any other tools/mega.nz website.

At least that was the state when I first wrote megatools.

So yes, it's doable, but it would be very limited or incompatible with other tools. If you need sync, you can probably use MEGAsync.

**Comment by i30817** [comment]
As i wrote before, megasync doesn't care about extra files. More, i haven't tried megacopy yet too much to see if it's different, but i think megasync actually sucks at non-private use.

This is because you need to copy a public folder into your own account before you can 'megasync' it, and therefore you need to *copy it every time you want to check updates on a public folder*. Thinks stinks and i can't help but think it's on purpose.

**Comment by i30817** [comment]
Basically, i'd even appreciate very much a simple 'rmlocal' tool that would delete files on a dir *not* on the remote dir, before using MegaSync even if you don't want to implement the 'this is a different file now and needs a update' functionality.

Because MegaSync is super dumb and doesn't have this simple option.

**Comment by i30817** [comment]
BTW, if anyone's interested, currently i'm doing this to sync public folders and delete the extra files:

1. import the the public folder to your cloud, deleting previous version if you had it.
2. `find ./<dir> -depth | grep -Fxvf <(megals -u <email> -p <password> -R /Root/<dir> | sed 's/\/Root/\./') | xargs rm -vr`

This finds all files on the dir, filters out those that aren't in the cloud on the same dir, 'translates' the path and removes them.

email and password are from your cloud, dir is what dir the local folder you want to update is on remote and local. They should be named the same and you should be careful not to put a '/' at the end because megals will return without '/' at the end and then this will delete the local folder instead of just the out of data files.

Then i use megasync and be careful to set upload speed to 0 to make sure i don't upload anything (and if it indicates it wanted to, delete that file right way).

**Comment by armandg** [comment]
How about implementing same feature that `youtube-dl` has, the `--continue` flag.

```
-c, --continue
              Force resume of partially downloaded files.  By default, youtube-dl
              will resume downloads if possible.
```

**Comment by megous** [comment]
@armandg That is already implemented (without an option to disable it), also this thread is about something else.

**Comment by armandg** [comment]
@megous I am obviously out of my element, and will disappear from this thread.

**Comment by megous** [comment]
If sync gets implemented, this will be part of it. So let's move this to #20
