### ISSUE TITLE
Logging in without exposing the password

### ISSUE THREAD

**Issue by miskolc** [megous/megatools#279]
I see that you can use megatools by either passing the password **interactively** when you are asked for it or by passing it to the `-p`  **flag** in the command line. The problem with the **first** approach is that it doesn't play well with Configuration software like Ansible, Puppet and Chef, the problem with the **second** approach is that it remains store in our bash history. Is there **another** approach to pass the password to `megatools`, like a **file**? How should the file format look like?

**Comment by christarazi** [comment]
You can use the [megarc](https://github.com/megous/megatools/blob/d8f96e9ad31d2ee2bf6bc9410925b28b44d95c6f/docs/megarc.txt) file.

**Comment by YashGulati** [comment]
this issue can be closed (i guess)

**Comment by ViperCode7** [comment]
MAN, section 5, CONFIGURATION FILES, or --help-all

I used it like this --config=U:\mega.ini, where the ini is on a truecrypt drive.

**Comment by gui-paredes** [comment]
@ViperCode7 I am curious about your solution. You store the data in a truecrypt drive, but don't you have do decrypt it, allowing access to the mega.ini file with the credentials, in order to use it in megatools? Doesn't that mean that the mega.ini becomes unprotected?

**Comment by ViperCode7** [comment]
Obviously, but otherwise I don't see a way to NOT expose the password via command path, batch scripts or from any logs or other apps that might log params and command paths of apps.
As a cli you'll always expose something or be ready to type it in manually every time it is needed and in batches that's a painful way to go about it.
Anyway, that is my way. Another approach would be to make the ini at the beginning of any batch session and destroy it at its end.

**Comment by gui-paredes** [comment]
Hmm.. I see. I was hoping that you had found a way to keep your credentials encrypted, but also accessible for megatools to read when needed. Thanks for your quick answer!
