### ISSUE TITLE
Console output doesn't support Unicode symbols

### ISSUE THREAD

**Issue by smx06** [megous/megatools#330]
When downloading files with national chars in the filename all is ok , but output to console (or redirected to file >out.txt) gives ??? in place of national symbols (Korean in my case)
OS: Arch Linux (code page is Ok)

**Comment by megous** [comment]
Megatools uses glib2 library, which internally uses UTF-8 for everything, and converts to the character set that you have set up on your distro automagically. It needs to have correct environment variables set, and I musn't have made any mistakes. :) Also there must be a mapping from UTF-8 to the charset you use for characters that are in the filenames of files you're currently downloading. Lot's of moving parts to say the least.

For starters, this would help:

    env | grep 'LC\|LANG'

Unless you have this set:

    https://developer.gnome.org/glib/stable/glib-running.html#G_FILENAME_ENCODING

files are saved in UTF-8 encoding. So if their names look correctly to you on disk, and garbled in output from megatools, then glib is trying to do some conversion, because it determined that terminal is non-UTF8.

**Comment by megous** [comment]
No response for too long. Closing.
