### ISSUE TITLE
limit upload speed

### ISSUE THREAD

**Issue by fabianmaass** [megous/megatools#36]
hey,

it would be cool if one could set an upload-speed limit for megaput. preferably via option parameter and/or in the configuration file.

thanks

**Comment by magamig** [comment]
Additionaly, a download-speed limit would also be a great improvement!

**Comment by Fitito** [comment]
Yeah please, is a great feature !

**Comment by megous** [comment]
You can add one parameter to curl, and the speed will be limited. :)

http://curl.haxx.se/libcurl/c/CURLOPT_MAX_RECV_SPEED_LARGE.html
http://curl.haxx.se/libcurl/c/CURLOPT_MAX_SEND_SPEED_LARGE.html

Just grep the code for curl_easy_setopt and try it. :)

**Comment by gaberad** [comment]
Hi, do you still have any plans on adding upload/download speed limit as a parameter/config file option?

For example, having the parameter/option to limit speeds would enable limiting speeds if it's run during the day, but overnight it can run with no limits etc.

Setting CURLOPT_MAX_SEND_SPEED_LARGE/CURLOPT_MAX_RECV_SPEED_LARGE in http.c > http_new worked, but then you're hard coded into those values. I could probably look into where to add and how to use parameters/config options, but I figure I'd wait to see what you're planning.

Then there's also the windows binaries, I'm not exactly sure on how to compile/build it on windows.

**Comment by dilworks** [comment]
Just learned about Megatools, but having no (direct/user-configurable) control over the upload/download speeds is pretty much a dealbreaker for my particular use cases (a home DSL on which I'm not the sole user, can't really use QoS on my router, etc, etc)

So, bumping this? I can recompile, but I really don't want to have a separate set of binaries for each speed limit I need to set depending on time of day or something.

**Comment by megous** [comment]
You can perhaps do something simple like retrieving the limits from the environment variable and passing them to libcurl in http.c. Then you wouldn't need to modify much code.

    char* limit = getenv("MEGATOOLS_UPLOAD_LIMIT");
    if (limit)
       curl_setopt(..., atoi(limit));

I don't have time to search for the name of the option.

**Comment by dilworks** [comment]
Yeah, an environment variable sounds like a "easy way out", but I would prefer a more regular commandline param/settings file option.

I was checking the code. As I understand it:

- Every specific tool calls tool_init, where settings are read and commandline is parsed
- Then a new session is created with tool_start_session. A new Mega session struct is created there (mega_session_new is called), which in turn contains a new HTTP struct. However, mega_session_new doesn't have access to settings (the mega_session struct receive username/password later with mega_session_open)

So, for doing things properly, it would involve:

- Adding the relevant options/settings set to tools.c. I would suggest creating a new GOptionEntry array specific for network settings.
- Add a couple of methods to http.c for setting UL/DL speeds
- Call those from tools,c after mega_session_new. Now tools.c involves http.c directly, rather than going through mega.c


I'll try to come up with a patch later, should not be that hard considering I'm not a C guy :D

**Comment by megous** [comment]
Not exactly. Http struct in the session is only used for REST API calls. Data connections use different http structs.

You'd probably need to add new options to basic_options. Save them to session struct during tool_start_session, and apply them to http structs created in mega_session_{put,get,dl}, right around the time http_set_progress_callback is called.

The same approach could be used for other curl options people requested in the past, like proxy settings.

Thanks. :)

**Comment by dilworks** [comment]
Took a while to start working on this, but here I am~

My notes so far:

- I'm going with a separate network_options, rather than adding stuff to basic_options since these are... well, network-related settings. Plus it opens room for future improvements (proxy settings being a frequently requested one, but I'm not going to work on that one)
- Not all tools call tool_init - there is a shortened version (tool_init_bare) which is similar except that it doesn't load username settings. megadl and megareg are the only ones using that function. But now that we have to deal with network settings (which are of concern for megadl), I wonder if both versions could be condensed into one, with an extra argument...
- Obviously not all tools would have use for UL/DL settings (megadl/megaget only needs DL, megaput only needs UL, and megacopy can use both), yet because those global options are set on tools.c, all tools end getting those on their commandlines, want them or not. I guess that in a future, those options should be moved and parsed by the respective tools that need them. But I would like to store them on the settings file, yet NONE of the tools parse it. Hmmm...

At least I got the speed settings loaded. Time to hook them in the relevant places!

**Comment by megous** [comment]
Network options group seems like a nice idea. Given that either the tool downloads or uploads the bulk data, never both, it should be less cumbersome to just have a single universal --limit-speed option.

**Comment by dilworks** [comment]
Yup, it would be much easier that way, commandline-wise it makes a lot of sense since you're effectively doing only one thing at a time. Most likely I'll go that way.

But for those relying on settings files for storing their preferred UL/DL speeds (remember: asymmetrical connections are still the norm on most of the world), I would prefer to keep both settings separate.

What I'm going to do then is to expose a single commandline limit-speed option, which will set the same value for both UL/DL. For those that want different speeds for both directions, then stick to the config file.

Thanks for the hints!

**Comment by megous** [comment]
Finished in 1.9.98
