### ISSUE TITLE
Documentation missing needed dependencies for compiling

### ISSUE THREAD

**Issue by Ryan-Myers** [megous/megatools#391]
I've been working on compiling this library on my Debian Linux distro, and I've been having a hell of a time getting various errors, despite following the documentation in the README. I figured I would help others, and hope that you can update the documentation to reflect a few packages missing in the list of required ones. I found that I could not get things compiling without these extra Debian packages: **docbook-xml libxml2-utils**. Without those two packages I couldn't build the docs.

**Comment by megous** [comment]
Thanks. That's somewhat unexpected, since asciidoc should probably depend on these packages. Looks like libxml2-utils is a required  dependency, but decbook-xml got demoted from recommended to a suggested dependency these packages are just listed as recommended:

  https://packages.debian.org/buster/asciidoc-base

Though all this is only relevant for developers building from git and should not be necessary if people are using the regular source code tarball.
