### ISSUE TITLE
How to gather a link after an upload.

### ISSUE THREAD

**Issue by maxisme** [megous/megatools#394]
After running:

```
$ file_name="test.txt"
$ mkdir /tmp/dir/
$ echo "hi" > /tmp/dir/$file_name
$ megacopy -l /tmp/dir/ -r /Root
```

It will return:

```
F /Root/test.txt
```

I would then like to find the link for this file:

I have tried this:
```
megals -e | grep $file_name | cut -d ' ' -f4
```
Which seems to **sometimes** work. How would you recommend I do this?

**Comment by megous** [comment]
Link has to be created. Simply use megals -e /Root/test.txt

**Comment by megous** [comment]
Seems like alignment is wrong by 3 characters since we removed .co from the mega's links in the past.

Anyway, you can just trim and collapse the whitespace and split line by a space and if the result has two items, the first one will be the exported file link.

I'll add a special export command, that will have a easier to use interface without the padding.

**Comment by maxisme** [comment]
Awesome. Yeah I am just doing the cut above!

**Comment by megous** [comment]
https://github.com/megous/megatools/commit/f19cf39067c3b9746d1d812bb1b18fdbf2144d8e
