### ISSUE TITLE
Server returned error EEXPIRED

### ISSUE THREAD

**Issue by mayara-ogliari** [megous/megatools#411]
Ao criar uma nova conta no mega.nz megatools está retornando a seguinte falha de conexão:

ERROR: Can't login to mega.nz: API call 'us' failed: Server returned error EEXPIRED

Esse erro não ocorre com contas mais antigas

**Comment by megous** [comment]
Expired session? Try removing the /tmp/*.megatools.cache files.

**Comment by SSoft7** [comment]
> Expired session? Try removing the /tmp/*.megatools.cache files.

Just removed, did not work.

**Comment by megous** [comment]
Expired account? 'us' is a login call, so not much else can sensibly be expired at that point.

**Comment by mayara-ogliari** [comment]
I removed the .megatools.cache files but it still gives the same error.

**Comment by mayara-ogliari** [comment]
> Expired account? 'us' is a login call, so not much else can sensibly be expired at that point.

How can I solve this?

**Comment by SSoft7** [comment]
> Expired account? 'us' is a login call, so not much else can sensibly be expired at that point.

Its free account not sure why it would expire. Made a fresh new account and same result.

**Comment by megous** [comment]
@mayara-ogliari 

I don't know.

Does it happen with their website too?

**Comment by SSoft7** [comment]
> @mayara-ogliari
> 
> I don't know.
> 
> Does it happen with their website too?

Nope, Login and upload are working fine on their website.

**Comment by mayara-ogliari** [comment]
@megous 

With this account I have access to mega.nz and if I use an old account it sends files via megaput to mega.ns

**Comment by mayara-ogliari** [comment]
This error is occurring in new accounts created this week

I tested with 2 new accounts created and is giving the same error

may be some incorrect file inside the Debian server?

**Comment by megous** [comment]
This error is not documented. It is used only for indicating expired download/upload links, and for account creation/cancelation tokens in their web client code. So... either they're repurposing it for something new, or I don't know.

You may try masking the megatools, so that they look like web browser accessing mega.nz. There's a code for it in http.c, maybe it helps.

**Comment by megous** [comment]
https://github.com/megous/megatools/blob/master/lib/http.c#L34

Change to

//#define STEALTH_MODE

to

#define STEALTH_MODE 1

and recompile.

**Comment by megous** [comment]
They've added a new registration/authentication method a few days ago. Website first fetches account version via us0 call. If it sees that it's the old style account, it does things differently. Megatools don't support this new method, so only work for accounts registered with the old method.

**Comment by megous** [comment]
Did you create the account that doesn't work with megatools or on their website?

**Comment by mayara-ogliari** [comment]
I created direct on mega.nz through the site

**Comment by megous** [comment]
Try creating via megatools, that should still give you the old style account.

**Comment by mayara-ogliari** [comment]
ok

**Comment by mayara-ogliari** [comment]
It is forecast to fit this into megatools?

**Comment by SSoft7** [comment]
@megous so megatools can be fixed (later) for this new accounts right?

**Comment by megous** [comment]
Good to know. So I guess that's the way to go in the meantime.

No forecast. Patch to the webclient that changed the login mechanism is like 17 000 lines of code. Though luckily only the smaller part of that is directly related to the protocol change. But still, it's not something I'm excited about going through. I'll wait to see if they also update the API documentation.

**Comment by megous** [comment]
If someone wants to keep an eye on the docs update, or analyze what's different from the code drop, that would help. It's this change:

https://github.com/meganz/webclient/commit/a2786d490244348b57fa2b5c0696194620f809e3

**Comment by megous** [comment]
Oh, there's gonna be no documentation. Mega.nz even decided to remove most of the previously existing protocol docs, so the only way is to reverse engineer the protocol changes from the code.

**Comment by mayara-ogliari** [comment]
Good Morning

Now in the morning the generation of new accounts by megareg

**Comment by megous** [comment]
I don't understand.

**Comment by mayara-ogliari** [comment]
It is not possible to create accounts by megareg

is returning the error:
ERROR: Registration failed: API call 'uc' failed: Server returned error EEXIST

**Comment by megous** [comment]
That's because it already exists for that emial.

**Comment by mayara-ogliari** [comment]
OK

I'll review the email.

**Comment by extensionsapp** [comment]
@megous how long will it take to fix the problem?

**Comment by megous** [comment]
It's probably 4-8hours of work, if all the necessary crypto is supported by openssl

**Comment by LuNiKoFf** [comment]
@megous any news about new mega account ? thx

**Comment by megous** [comment]
No news. I haven't been looking into it.

**Comment by extensionsapp** [comment]
Megatools will no longer be supported?

**Comment by megous** [comment]
The code is available, anyone who needs to login to new accounts created on mega.nz website can implement new logins. I'd pull the changes.

I don't need it, my old accounts still work and as someone else reported, if you register new account with megatools, you'll still be able to login. I haven't tested that.

**Comment by vinnytroia** [comment]
the code is still available how/where? i have pulled/compiled the latest version of the code and getting the same error

**Comment by dobaniashish** [comment]
@megous Can you give a tutorial to build single binaries for CentOS and Windows? I can try to implement the new login system.

**Comment by dobaniashish** [comment]
@megous I have read the README file before and was able to successfully build. I was asking How to build standalone static builds. https://github.com/megous/megatools/blob/master/README#L137

**Comment by megous** [comment]
@dobaniashish 

I used this to build the musl C toolchains: https://github.com/richfelker/musl-cross-make

For windows, you can use https://sourceforge.net/projects/mingw-w64/files/mingw-w64/mingw-w64-release/

You'd have to build all the dependencies with `configure --enable-static --disable-shared --prefix=/your/prefix` or equivalent and make sure you don't accidentally use the host's header or library files when building. It's a ton of work to set all that up, and I don't have a guide written up.

**Comment by sjuswede** [comment]
I ran into the same problem. Was trying to download and ran into the limit, so I created an account and paid for access. When I try to use the new account with the latest experimental build of megatools I get the EEXPIRED error.

How can I work around this?

**Comment by megous** [comment]
You can not. Mega.nz added a new login type and a registration flow a month ago (that was incompatible with all other existsing clients other than their official ones), and new accounts when created via a mega.nz website, can't be used with megatools, ATM.

Accounts created with megatools, and old accounts, should still work with any tool though as reported by other users.

You can use their client.

**Comment by megous** [comment]
I've added a note to the website.

**Comment by sjuswede** [comment]
They have a command line client? I didn't know that. I will try with that, thanks!

It's been painful to use the website to download and move files from my laptop to my file server, one file at the time, and some files are so big I will have to clear out space on the laptop. It's also slow, due to the clunky way the web app works. Command line straight from the file server is much better, and I thought megatools was my only real choice.

**Comment by wilterporto** [comment]
Resolvido (Solved)
Usando CentOS 7
Exclui a conta que criei no site e criei pela linha de comando seguindo o modelo abaixo.

# megareg --register --email your@email.com --name "Your Name" --password "Your Password"

**Comment by kkm** [comment]
Anyone fix that?

**Comment by ahmedtds** [comment]
Is there another cli tool that can handle new new accounts other than mega's own megacmd? megacmd is very bloated.

**Comment by rs3mk** [comment]
work in File & Image uploader

![mega00](https://user-images.githubusercontent.com/19628943/62667649-3d630d00-b94e-11e9-8b24-7a6f2b56d6ad.png)
![mega01](https://user-images.githubusercontent.com/19628943/62667650-3d630d00-b94e-11e9-903c-5b0982105689.png)

**Comment by jonahamada** [comment]
i just created an account mega for the first time , i installed megatools on ubuntu from its repositories (using apt) and i faced the same issue , i went back to mega.nz on browser and i found mega-cmd cli for linux/mac/other https://mega.nz/cmd 
# purge megatools and install megacmd.deb
# login to your account
mega-login you@email password 
and all is fine yay !

**Comment by liar666** [comment]
Hi all,

Indeed, this new auth is quite annoying. Also, I noticed that the new accounts are created with 15GB instead of 50Gb :{ 

I found a very simple workaround, but unfortunately it can take some time to set up:

The simplest setting is with opening 2 browsers, each one will manage a single mega account:

1. Use a first browser (e.g. FF), login into your original MEGA account (nammed accountSrc below) and move everything into a **single directory**
2a. Create a **new account using megareg** (nammed accountDest below)
2b. Use a **second browser** (e.g. Chromium) to **validate the account**.
[2c. Be sure to **logout from accountDest**] -> see 4c.
3. Use the first browser (FF) to **get the link** for sharing the single **big directory** of accountSrc
4a. Go back to the second browser (Chromium) and **visit to the sharing URL**
4b. The content of the shared directory should appear and there is an option to **import** the data into your mega account.
4c. Choose this option and import the whole directory into accountDest. It might import the dir directly into your accountDest if you did not log out in step 2c. Otherwise you'll be ask to connect to your "MEGA account". Here, select the login/pass for the accountDest.
This operation can take some time, even if all the data is not actually copied.
**NOTE: sometimes at this step, my browser simply blocks on the page with the looping mega wheel waiting for the data to be "copied" I waited hours and nothing happened... In such cases, I go back to the shared link URL and import only a single sub-directory, then go back to the shared url, etc to import the content piece by piece. Quite long but works :{**
5. **Verify that all the data has been correctly and totally imported**. This is important as we will trash the original accountSrc!!!!
6. Go to the first browser/account and ask mega to **destroy accountSrc**
7. Rapidly **recreate** accountSrc with **megareg**
8. Copy your data back to this accountSrc-new using a similar procedure as steps 3/4

TADA! new-OLD account has 50GB and is accessible through megatools \o/

The procedure might be simplified (not loging out from the accounts or using a single browser), but this is how I did it and it worked :)

**Comment by erotavlas-turbo** [comment]
I was able to use megatools by following the suggestion of @wilterporto.
Does [megatools](https://megatools.megous.com/man/megatools.html) removed the sync command? How can I sync with it? Or it is not possible and I have to use megacmd?

**Comment by megous** [comment]
Someone contributed a support for a new login flow, so v2 accounts are now supported.

**Comment by marcelomendes** [comment]
I'm having this same issue (megatools 1.10.3-1 on Debian). Any way to fix this without have to create a new account?

**Comment by ahmedtds** [comment]
> 
> 
> I'm having this same issue (megatools 1.10.3-1 on Debian). Any way to fix this without have to create a new account?

use latest build from here: https://megatools.megous.com/builds/experimental/

**Comment by maltfield** [comment]
It looks like the megatools NEWS file lists `megatools v1.11.0` (released 2022-05-19) has added `Login v2 support`

 * https://megatools.megous.com/builds/NEWS

```
megatools 1.11.0 - 2022-05-19
=============================

This release introduces new features.

Improvements:

- Megatools now install a single `megatools` executable, where former
  `megaXYZ ...` commands now have to be executed as `megatools XYZ ...`.
- Implemented PKP (public key pinning for mega.nz's API server). Megatools
  no longer use public certificate authorities to verify API server's
  authenticity. If you use software that MITM's your web traffic, megatools
  will not allow this anymore.
- Windows builds no longer need any special console setup to support UTF-8.
  It just works out of the box.
- Support new public folder URLs in `dl`
- Build system moved to meson
- New `test` command for checking if file exists
- New `export` command for creating public links for private files
- Login v2 support
- Upload reliability improvements
```
