### ISSUE TITLE
Megadl should create local folder

### ISSUE THREAD

**Issue by Porkepix** [megous/megatools#432]
Megadl should create the local folder when downloading a whole Mega folder (or at least offer to do it).

**Comment by megous** [comment]
Just `mkdir -p` first? Megatools will create all the other folders, but creating the target folder is not common for any other Linux tools. cp, wget, mv, curl, ... will not create the directory either. I guess, it's better, because it helps you catch typos (you get an error, instead of silent  creation of a wrong directory).

**Comment by Porkepix** [comment]
Well, this was all in the idea of do things faster. Imho it would make sense for me offering to download the whole folder completely, including the root folder.
And currently it's not possible either to give target on the command line like you would with (s)cp for example, so it means you need to mkdir first, then cd then use megadl.

Sure it's only three commands, could always be improved though :)
But your mileage may vary :P

**Comment by vitorgalvao** [comment]
> And currently it's not possible either to give target on the command line

It is. Use a [here string](https://bash.cyberciti.biz/guide/Here_strings). So for example, if you want file 5, you’d do: `megadl --choose-files '<your_mega_link>' <<< 5`.

**Comment by Porkepix** [comment]
> > And currently it's not possible either to give target on the command line
> 
> It is. Use a [here string](https://bash.cyberciti.biz/guide/Here_strings). So for example, if you want file 5, you’d do: `megadl --choose-files '<your_mega_link>' <<< 5`.

Thanks for the tip, I didn't knew about this.
However, this is not what I meant: I talked about giving on the command line the directory where you wanted to download the files (one different from the one you currently are running the command from).

**Comment by vitorgalvao** [comment]
> I talked about giving on the command line the directory where you wanted to download the files

That’s `--path`. As in, `megadl --path="${HOME}/Downloads" '<your_mega_link>'`.

See `megadl --help`.

**Comment by Porkepix** [comment]
My bad, missed that one. Actually, I tried to give it as a independent argument without any option after the link, exactly the same way you do a (s)cp for example.
I might have mixed it up with megacmd, official's mega tool I also gave a try in the same time.

**Comment by megous** [comment]
Let's leave this as an explicit operation.

**Comment by mohkale** [comment]
@megous 

I'm late to the party and sorry for re-opening this issue but I still think this should be considered. I often collect mega links to download into a text file and then run:

```sh
xargs -I {} -r -d '\n' -a ./mega.txt megadl --limit-speed 1000
```

This downloads all of the URLs in mega.txt but sadly it dumps them all to the cwd or a path I specify but there's no way to disambiguate them. If I download an 3 albums I'm hosting on mega then all the songs are cluttered into the cwd.

I've been stripping out the URLs (keeping just the hashes) and using `parallel` so that I can create both a unique containing directory and download the files at once but these titles give no indication as to the contents and in the end I have to manually look them up and apply a title myself afterwards.

```sh
parallel --max-procs 1 -u -I {} -r -d '\n' -a ./mega.txt mkdir -p {} '&&' megadl --limit-speed 1000 https://mega.nz/folder/{} --path {}
```

If the intention is to batch download files, megadl should at least give an option to group the files into directories matching the remote name of the files IMO.

**Comment by vitorgalvao** [comment]
@mohkale [This repo is no longer monitored.](https://github.com/megous/megatools#repostiory-has-been-moved)

**Comment by f-o** [comment]
> > And currently it's not possible either to give target on the command line
> 
> It is. Use a [here string](https://bash.cyberciti.biz/guide/Here_strings). So for example, if you want file 5, you’d do: `megadl --choose-files '<your_mega_link>' <<< 5`.

With the help of this comment, I figured out how to achieve what OP (and myself) wanted to all along.

When you use the interactive "choose files" menu, it allows you to select the root folder for download.
This option will always be no. 1, as it's the root.

The solution to your problem, and the answer to how to make individual folders, with all the files within, is simply to run the following command:
`megadl --choose-files https://mega.nz/folder/XXXXX <<< 1`

That's it.
